### PR TITLE
Finishing chapters 7 to 9 advanced path of Elixir

### LINKED ISSUE #20: Advanced chapter 7 to 9
## Dependencies and umbrellas
Starting with dependencies and umbrella projects
### Dependencies
The external dependencies in a project can be like so, with the name of the dependency and the version associated:
```elixir
def deps do
  [{:plug, "~> 1.0"}]
end
```
You can also fetch dependencies and compile it with the tasks provided by mix:
```bash
mix deps.get 
```
and
```bash
mix deps.update
```
And the internal dependencies can be placed like so, in this case importing the kv module:
```elixir
def deps do
  [{:kv, git: "https://github.com/YOUR_ACCOUNT/kv.git"}]
end
```
### Umbrella projects
I started a new umbrella project where will be all the apps for this practice:
```bash
mix new kv_umbrella --umbrella
```
Every project in /apps needs to have the shared configurations of the umbrella project, like so:
```elixir
build_path: "../../_build",
config_path: "../../config/config.exs",
deps_path: "../../deps",
lockfile: "../../mix.lock",
```

### Task and gen_tcp
Wrote an basic server using tasks and gen_tcp, firstly creating a method to accept connections in a port, and then serving that connections with a Task.Supervisor:
```elixir
defp loop_acceptor(socket) do
    {:ok, client} = :gen_tcp.accept(socket)
    # We start a serve task with the Task Supervisor
    {:ok, pid} = Task.Supervisor.start_child(KVServer.TaskSupervisor, fn -> serve(client) end)

    # Without this the acceptor will bring down all the clients if it crashed (Like when quitting a client)
    :ok = :gen_tcp.controlling_process(client, pid)
    loop_acceptor(socket)
end
```
The serve function inside the task just reads the line from the socket and then replies it to the socket in an infinite loop:
```elixir
# This method reads a line from the socket and then replies the same line to the socket
  defp serve(socket) do
    socket
    |> read_line()
    |> write_line(socket)

    serve(socket)
end
```

### Doctests
Using doctest to document and make tests at the same time in a specific function, considering a test and a function like so:
```elixir
@doc ~S"""
  Parses the given `line` into a command.

  ## Examples

    iex> KVServer.Command.parse "CREATE shopping\r\n"
    {:ok, {:create, "shopping"}}
  """
  def parse(line) do
    case String.split(line) do
      ["CREATE", bucket] -> {:ok, {:create, bucket}}
    end
  end
```
The example above can be tested with ExUnit and will only pass if the examples in the doc get the same result in the function, we can test the doc like so:
```elixir
defmodule KVServer.CommandTest do
  use ExUnit.Case, async: true
  doctest KVServer.Command
end
```

### with
The with allow us to do something similar to a pipeline (|>), to short our code,
for example, doing a flow like this:
```elixir
msg =
      with {:ok, data} <- read_line(socket),
           {:ok, command} <- KVServer.Command.parse(data),
           do: KVServer.Command.run(command, KV.Registry)
```
### testing the server with gen_tcp
To test the server we need to clean the state of the application like so:
```elixir
setup do
    Application.stop(:kv)
    :ok = Application.start(:kv)
  end
```
And then create a socket connection to play like a cliente connecting to the server:
```elixir
setup do
    opts = [:binary, packet: :line, active: false]
    # This connects to the server in the port 4040
    {:ok, socket} = :gen_tcp.connect('localhost', 4040, opts)
    %{socket: socket}
  end
```
And then make the requests:
```elixir
test "server interaction", %{socket: socket} do
    assert send_and_recv(socket, "UNKNOWN shopping\r\n") == "UNKNOWN COMMAND\r\n"
  end

  # Method to send and receive messages working as a client
  defp send_and_recv(socket, command) do
    :ok = :gen_tcp.send(socket, command)
    {:ok, data} = :gen_tcp.recv(socket, 0, 1000)
    data
  end
```

### PR DESCRIPTION
**Pull request by CristhianRodriguezMolina**
Finishing with:
- Dependencies and umbrellas
- Task and gen_tcp (The kv_server)
- Doctests, patterns and with (Finishing the kv_server)

### CODE REVIEW

File: advanced/kv_umbrella/apps/kv/lib/registry.ex [hunk 1]
```diff
@@ -30,11 +30,11 @@ defmodule KV.Registry do
...
 
-  @doc """
-  Looks up for all the buckets
+  # @doc """
+  # Looks up for all the buckets
 
-  Returns %{name => PID, ...}
-  """
+  # Returns %{name => PID, ...}
+  # """
```
Comment (luishurtado) [inline advanced/kv_umbrella/apps/kv/lib/registry.ex]: Why did you comment out this?

**Review by luishurtado — CHANGES_REQUESTED** [review]

File: advanced/kv_umbrella/apps/kv/lib/registry.ex (hunk 1 above)
Comment (CristhianRodriguezMolina) [reply advanced/kv_umbrella/apps/kv/lib/registry.ex]: Because i commented a function right below, and then the @doc shows me a warning cause there is no function, but i forgot delete that sorry, ill delete it right now.

**Review by luishurtado — APPROVED** [review]
